"""migration_m2m_materials

Revision ID: 2c6b7ba017bb
Revises: c24375df89dc
Create Date: 2026-05-21 10:35:26.467530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c6b7ba017bb"
down_revision: Union[str, Sequence[str], None] = "c24375df89dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calculation_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("condenser_id", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column("input_data", sa.JSON(), nullable=False),
        sa.Column("output_data", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["condenser_id"],
            ["condensers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calculation_results_condenser_id"),
        "calculation_results",
        ["condenser_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calculation_results_created_at"),
        "calculation_results",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calculation_results_id"), "calculation_results", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_calculation_results_method"),
        "calculation_results",
        ["method"],
        unique=False,
    )
    op.create_table(
        "condenser_material_association",
        sa.Column("condenser_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["condenser_id"], ["condensers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["material_id"], ["materials.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("condenser_id", "material_id"),
    )
    op.drop_constraint(
        op.f("condensers_material_id_fkey"), "condensers", type_="foreignkey"
    )
    op.drop_column("condensers", "material_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "condensers",
        sa.Column("material_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("condensers_material_id_fkey"),
        "condensers",
        "materials",
        ["material_id"],
        ["id"],
    )
    op.drop_table("condenser_material_association")
    op.drop_index(
        op.f("ix_calculation_results_method"), table_name="calculation_results"
    )
    op.drop_index(op.f("ix_calculation_results_id"), table_name="calculation_results")
    op.drop_index(
        op.f("ix_calculation_results_created_at"), table_name="calculation_results"
    )
    op.drop_index(
        op.f("ix_calculation_results_condenser_id"), table_name="calculation_results"
    )
    op.drop_table("calculation_results")
    # ### end Alembic commands ###
