"""Initial full schema

Revision ID: c24375df89dc
Revises:
Create Date: 2026-04-21 08:32:08.073235

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c24375df89dc'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('thermal_conductivity_points', sa.JSON(), nullable=False),
    sa.Column('full_properties', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_materials_material_uuid'), 'materials', ['material_uuid'], unique=True)
    op.create_table('condensers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_condenser', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('doc_num_thermo_calc', sa.String(), nullable=True),
    sa.Column('doc_num_assembly', sa.String(), nullable=True),
    sa.Column('doc_num_passport', sa.String(), nullable=True),
    sa.Column('diameter_internal', sa.Float(), nullable=False),
    sa.Column('wall_thickness', sa.Float(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('main_length', sa.Float(), nullable=False),
    sa.Column('main_count', sa.Integer(), nullable=False),
    sa.Column('builtin_length', sa.Float(), nullable=True),
    sa.Column('builtin_count', sa.Integer(), nullable=True),
    sa.Column('aircooler_count', sa.Integer(), nullable=True),
    sa.Column('passes_main', sa.Integer(), nullable=False),
    sa.Column('passes_builtin', sa.Integer(), nullable=True),
    sa.Column('ejectors_count', sa.Integer(), nullable=False),
    sa.Column('mass_flow_steam_nom', sa.Float(), nullable=False),
    sa.Column('mass_flow_air', sa.Float(), nullable=False),
    sa.Column('water_flow_limits', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condensers_name_condenser'), 'condensers', ['name_condenser'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_condensers_name_condenser'), table_name='condensers')
    op.drop_table('condensers')
    op.drop_index(op.f('ix_materials_material_uuid'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###
